### ISSUE TITLE
Error Model Not Found

### ISSUE THREAD

**Issue by gorin-research-repo** [amine0110/yolo-sam#1]
Downloaded as zip,
Unzipped to C drive,
Loaded folder in Visual Code,
PIP install all dependencies
Run main.py and get the error below. 

Traceback (most recent call last):
  File "c:\yolo-sam-main\main.py", line 512, in <module>
    app = ImageFrame(ttk_root)
  File "c:\yolo-sam-main\main.py", line 119, in __init__
    sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
  File "c:\yolo-sam-main\segment_anything\build_sam.py", line 38, in build_sam_vit_b
    return _build_sam(
  File "c:\yolo-sam-main\segment_anything\build_sam.py", line 104, in _build_sam
    with open(checkpoint, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'model/sam_vit_b_01ec64.pth'

Seems that the model is not building so I run the build_sam.py code but get this error: 

Traceback (most recent call last):
  File "c:\yolo-sam-main\segment_anything\build_sam.py", line 11, in <module>
    from .modeling import ImageEncoderViT, MaskDecoder, PromptEncoder, Sam, TwoWayTransformer
ImportError: attempted relative import with no known parent package
PS C:\yolo-sam-main>

**Comment by amine0110** [comment]
Hi,

You will require to download the model checkpoint from the official repo here: https://github.com/facebookresearch/segment-anything#model-checkpoints
